[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 10000
solc_version = "0.8.30"
evm_version = "osaka"
ffi = true
# Enable file reading permissions
fs_permissions = [{ access = "read-write", path = "./" }]


[profile.lite]
optimizer = false
solc_version = "0.8.30"
evm_version = "cancun"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
